version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:CHANGE_ME@db:5432/postgres?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=CHANGE_ME
    volumes:
      - /Users/jake/Documents/manga:/app/data
    depends_on:
      - 'db'
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: CHANGE_ME
    ports:
      - 5432:5432
