# Based on the following Github Action.
# https://github.com/ahmetozer/github-actions-multi-arch-container-ghcr.io

name: Build `main`

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: ⚙️ Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: ⚙️ Setup Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 👤 Login GHCR.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 🚀 Build and Publish Images
        run: |
          IMAGE_ID=$(echo ghcr.io/${{ github.repository }} | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # when the branch is main, replace main with latest
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          # Build and Publish container image
          docker buildx build --push \
          --tag $IMAGE_ID:$VERSION \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
